#prettier-ignore
apiVersion: v1
kind: Service
metadata:
  name: service-31008
  labels:
    {{- include "strawberry.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    {{- include "strawberry.selectorLabels" . | nindent 4 }}
